export const Login_Success = 'Login_Success'
export const Login_Pending = 'Login_Pending'
export const Login_Failure = 'Login_Failure'
export const Logout = 'Logout'
export const Check2FA_State = 'Check2FA_State'